apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-static
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
