apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: cluster-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.2
    helm:
      releaseName: longhorn
      valuesObject:
        # To use with ArgoCD, the pre-upgrade-checker job must be disabled
        helmPreUpgradeCheckerJob:
          enabled: false
        defaultSettings:
          logLevel: warn
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          host: longhorn.ops.mareshq.com
          tls: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
