apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  project: cluster-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.14.4
    helm:
      releaseName: cilium
      valuesObject:
        kubeProxyReplacement: true
        k8sServiceHost: cthulhu.k8s.vxm.cz
        k8sServicePort: 6443
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
