apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extra-storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: cluster-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: manifests/storageclass/
    repoURL: https://github.com/vojtechmares/cthulhunetes-gitops.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
