apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: cluster-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: operator
    repoURL: https://operator.min.io
    targetRevision: 5.0.10
    helm:
      releaseName: minio-operator
      valuesObject:
        console:
          replicaCount: 2
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            host: console.minio.cthulhunetes.net
            tls:
              - hosts:
                  - console.minio.ops.cthulhunetes.net
                secretName: minio-console-ingress-tls
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio-operator
