apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: cluster-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: manifests/
    repoURL: https://github.com/rancher/system-upgrade-controller.git
    targetRevision: 0.13.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: system-upgrade
